### ISSUE TITLE
Unable to run in Xcode

### ISSUE THREAD

**Issue by GitGleam** [zqqf16/Monster#1]
Downloading the source code and trying to run in Xcode it gives the following errors: 

"Cannot find 'NavigationSplitViewVisibility' in scope"
"Cannot find 'NavigationSplitViewVisibility' in scope"
"Cannot infer contextual base in reference to member 'detailOnly'"

Am I doing something wrong? 

Xcode Version 14.0 (14A309)

**Comment by zqqf16** [comment]
I'm using Xcode Version 14.0 beta 6 (14A5294g). 
`NavigationSplitViewVisibility` is a new api added in macOS 13.0. It is still in beta 😂
